registeries:
  - master: docker.afiniti.com
  - slave1: 172.16.30.235:5000/v2


rules:
  rule1: 
    afiniti-ui:
      tags: 
        - a
        - b
      source: master
      destination: 
      - slave1
      - slave2
  rule2:
    afiniti-ui:
      tags:
        - c
        - d
      source: master
      destination:
        - slave1
